### ISSUE TITLE
Feedback after initial trial

### ISSUE THREAD

**Issue by matmair** [j-huff/inventree-tui#1]
Hi there! Coming over from https://github.com/inventree/InvenTree/discussions/7410 I have a few bits of feedback - take or leave it, really cool what you have built already!

1) You might consider recommending pipx to ensure you tool is not disturbed by another tool requesting a different version of inventree
2) You get a pretty uninformative (for non-developers) error message when you forget to set either `INVENTREE_API_HOST` or `INVENTREE_API_TOKEN`. Providing actionable infos what to do might be good for beginners - maybe even providing where to get a token
3) The styles.css file seems missing in distribution
4) parts with no location set throw errors

Are you open to PRs for a few of those? I have local fixes for 3, 4 and probably 2

**Comment by matmair** [comment]
Short update - here are the fixes:
1) Will work after https://github.com/matmair/inventree-tui/tree/fix-entrypoint is merged - this fixes cli entry point handling (the old method resulted in the main class being called with instantiation)
2) https://github.com/matmair/inventree-tui/tree/add-error-msg - a bit crude but works
3) https://github.com/matmair/inventree-tui/tree/include-css-files
4) https://github.com/matmair/inventree-tui/tree/fix-part-serachresult-without-location

On a side note: I was not aware of textual - pretty awesome library to build cool stuff.
This tool has potential. I would like to feature it in a blog entry on inventree.org if that is fine for you

**Comment by j-huff** [comment]
Thank you, I'll have a look at these tomorrow. And yes, feel free to post about it anywhere. I should probably throw an MIT license on the repo just to be clear that Im happy for people to use it however they like.

Edit: I suppose tomorrow I'll have to look at the repo settings for making pull requests if you were unable to make them.

**Comment by matmair** [comment]
@j-huff pull request do work, I just did not want to flood your inbox without being sure you are cool with them. I have opened individual PRs for all of those and added some context to the individual changes. Closing this to reduce the noise.

A license would be nice for sure!
