### ISSUE TITLE
Hotkeys for tab selection and confirmation

### ISSUE THREAD

**Issue by matmair** [j-huff/inventree-tui#22]
I am using a [reTerminal](https://www.seeedstudio.com/ReTerminal-with-CM4-p-4904.html) with this and I would like to use the included buttons to switch tabs and confirm check-in/transfer. Would this be something you would be interested in merging @j-huff?

**Comment by j-huff** [comment]
Yeah that looks really neat. Just make sure to include a configuration setting with it being defaulted to off. Are there any additional dependencies?

**Comment by j-huff** [comment]
Oh, unless they are literally just f keys. Then we could have it defaulted to on.

**Comment by matmair** [comment]
It is just fn keys (you can configure which ones)

**Comment by j-huff** [comment]
yeah, go ahead and make a pull request. no configuration settings ~~need~~ *need* to be added, it can just always be on.
