### ISSUE TITLE
Bug? Token/Host enviroment variable name has changed

### ISSUE THREAD

**Issue by matmair** [j-huff/inventree-tui#23]
Token/Host environment variables need to be named inventree_inventree_... to work. This seems to be because the setting itself is named inventree_api_host.
@j-huff is this change intended? I can provide a PR if not

**Comment by j-huff** [comment]
definitely a bug. not sure how I didn't come across this already. PR would be appreciated.

**Comment by matmair** [comment]
Do you want the key in the config.yaml to be `inventree_api_host` or `api_host`?

**Comment by j-huff** [comment]
inventree_api_host. I think if you just remove the environment variable prefix from the settings config and keep the name as inventree_api_host that should fix it.

________________________________
